// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type Caisse struct {
	ID           string               `json:"id"`
	Balance      float64              `json:"balance"`
	TotalEntrees float64              `json:"totalEntrees"`
	TotalSorties float64              `json:"totalSorties"`
	CreatedAt    string               `json:"createdAt"`
	UpdatedAt    string               `json:"updatedAt"`
	Transactions []*CaisseTransaction `json:"transactions"`
}

type CaisseTransaction struct {
	ID            string  `json:"id"`
	Type          string  `json:"type"`
	Amount        float64 `json:"amount"`
	Description   *string `json:"description,omitempty"`
	Reference     *string `json:"reference,omitempty"`
	ReferenceType *string `json:"referenceType,omitempty"`
	Date          string  `json:"date"`
	CreatedBy     *string `json:"createdBy,omitempty"`
}

type CaisseTransactionInput struct {
	Type          string  `json:"type"`
	Amount        float64 `json:"amount"`
	Description   *string `json:"description,omitempty"`
	Reference     *string `json:"reference,omitempty"`
	ReferenceType *string `json:"referenceType,omitempty"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type Client struct {
	ID                 string     `json:"id"`
	ClientID           string     `json:"clientId"`
	Name               string     `json:"name"`
	Phone              *string    `json:"phone,omitempty"`
	Nn                 *string    `json:"nn,omitempty"`
	Address            *string    `json:"address,omitempty"`
	Avatar             *string    `json:"avatar,omitempty"`
	SponsorID          *string    `json:"sponsorId,omitempty"`
	Position           *string    `json:"position,omitempty"`
	LeftChildID        *string    `json:"leftChildId,omitempty"`
	RightChildID       *string    `json:"rightChildId,omitempty"`
	JoinDate           string     `json:"joinDate"`
	TotalEarnings      float64    `json:"totalEarnings"`
	WalletBalance      float64    `json:"walletBalance"`
	Points             float64    `json:"points"`
	NetworkVolumeLeft  float64    `json:"networkVolumeLeft"`
	NetworkVolumeRight float64    `json:"networkVolumeRight"`
	BinaryPairs        int32      `json:"binaryPairs"`
	Sponsor            *Client    `json:"sponsor,omitempty"`
	LeftChild          *Client    `json:"leftChild,omitempty"`
	RightChild         *Client    `json:"rightChild,omitempty"`
	Transactions       []*Payment `json:"transactions"`
	Purchases          []*Sale    `json:"purchases"`
}

type ClientInput struct {
	Name      string  `json:"name"`
	Password  string  `json:"password"`
	Position  *string `json:"position,omitempty"`
	SponsorID *string `json:"sponsorId,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	Nn        *string `json:"nn,omitempty"`
	Address   *string `json:"address,omitempty"`
	Avatar    *string `json:"avatar,omitempty"`
}

type ClientLoginInput struct {
	ClientID string `json:"clientId"`
	Password string `json:"password"`
}

type ClientTree struct {
	Root       *ClientTreeNode   `json:"root"`
	Nodes      []*ClientTreeNode `json:"nodes"`
	TotalNodes int32             `json:"totalNodes"`
	MaxLevel   int32             `json:"maxLevel"`
}

type ClientTreeNode struct {
	ID                 string  `json:"id"`
	ClientID           string  `json:"clientId"`
	Name               string  `json:"name"`
	Phone              *string `json:"phone,omitempty"`
	ParentID           *string `json:"parentId,omitempty"`
	Level              int32   `json:"level"`
	Position           *string `json:"position,omitempty"`
	NetworkVolumeLeft  float64 `json:"networkVolumeLeft"`
	NetworkVolumeRight float64 `json:"networkVolumeRight"`
	BinaryPairs        int32   `json:"binaryPairs"`
	TotalEarnings      float64 `json:"totalEarnings"`
	WalletBalance      float64 `json:"walletBalance"`
	IsActive           bool    `json:"isActive"`
	LeftActives        int32   `json:"leftActives"`
	RightActives       int32   `json:"rightActives"`
	IsQualified        bool    `json:"isQualified"`
	CyclesAvailable    *int32  `json:"cyclesAvailable,omitempty"`
	CyclesPaidToday    *int32  `json:"cyclesPaidToday,omitempty"`
}

type Commission struct {
	ID             string  `json:"id"`
	ClientID       string  `json:"clientId"`
	SourceClientID string  `json:"sourceClientId"`
	Amount         float64 `json:"amount"`
	Level          int32   `json:"level"`
	Type           string  `json:"type"`
	Date           string  `json:"date"`
	Client         *Client `json:"client,omitempty"`
	SourceClient   *Client `json:"sourceClient,omitempty"`
}

type CommissionInput struct {
	ClientID       string  `json:"clientId"`
	SourceClientID string  `json:"sourceClientId"`
	Amount         float64 `json:"amount"`
	Level          int32   `json:"level"`
	Type           string  `json:"type"`
}

type CommissionResult struct {
	CommissionsCreated int32   `json:"commissionsCreated"`
	TotalAmount        float64 `json:"totalAmount"`
	Message            string  `json:"message"`
}

type DashboardStats struct {
	TotalProducts    int32             `json:"totalProducts"`
	TotalClients     int32             `json:"totalClients"`
	TotalSales       float64           `json:"totalSales"`
	TotalRevenue     float64           `json:"totalRevenue"`
	ActiveClients    int32             `json:"activeClients"`
	LeftVolume       float64           `json:"leftVolume"`
	RightVolume      float64           `json:"rightVolume"`
	BinaryPairs      int32             `json:"binaryPairs"`
	TotalCommissions float64           `json:"totalCommissions"`
	NetworkBalance   float64           `json:"networkBalance"`
	MonthlySales     []*MonthlySales   `json:"monthlySales"`
	NetworkGrowth    []*NetworkGrowth  `json:"networkGrowth"`
	SalesStatus      *SalesStatus      `json:"salesStatus"`
	TopProducts      []*TopProduct     `json:"topProducts"`
	RecentActivity   []*RecentActivity `json:"recentActivity"`
}

type FilterInput struct {
	Search   *string `json:"search,omitempty"`
	DateFrom *string `json:"dateFrom,omitempty"`
	DateTo   *string `json:"dateTo,omitempty"`
	Status   *string `json:"status,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MonthlySales struct {
	Month   string  `json:"month"`
	Sales   float64 `json:"sales"`
	Revenue float64 `json:"revenue"`
}

type Mutation struct {
}

type NetworkGrowth struct {
	Month        string `json:"month"`
	NewClients   int32  `json:"newClients"`
	TotalClients int32  `json:"totalClients"`
}

type PagingInput struct {
	Page  *int32 `json:"page,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

type Payment struct {
	ID          string  `json:"id"`
	ClientID    string  `json:"clientId"`
	Amount      float64 `json:"amount"`
	Date        string  `json:"date"`
	Method      string  `json:"method"`
	Status      string  `json:"status"`
	Description *string `json:"description,omitempty"`
	Client      *Client `json:"client,omitempty"`
}

type PaymentInput struct {
	ClientID    string  `json:"clientId"`
	Amount      float64 `json:"amount"`
	Method      string  `json:"method"`
	Description *string `json:"description,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	Points      float64 `json:"points"`
	ImageURL    string  `json:"imageUrl"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
	Points      float64 `json:"points"`
	ImageURL    string  `json:"imageUrl"`
}

type Query struct {
}

type RecentActivity struct {
	ID          string   `json:"id"`
	Type        string   `json:"type"`
	Description string   `json:"description"`
	Date        string   `json:"date"`
	Amount      *float64 `json:"amount,omitempty"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type ResetClientPasswordInput struct {
	ClientID    string `json:"clientId"`
	NewPassword string `json:"newPassword"`
}

type ResetPasswordByEmailInput struct {
	Email       string `json:"email"`
	NewPassword string `json:"newPassword"`
}

type ResetPasswordInput struct {
	ID          string `json:"id"`
	NewPassword string `json:"newPassword"`
}

type Sale struct {
	ID         string   `json:"id"`
	ClientID   string   `json:"clientId"`
	ProductID  *string  `json:"productId,omitempty"`
	Amount     float64  `json:"amount"`
	PaidAmount *float64 `json:"paidAmount,omitempty"`
	Quantity   int32    `json:"quantity"`
	Side       *string  `json:"side,omitempty"`
	Date       string   `json:"date"`
	Status     string   `json:"status"`
	Note       *string  `json:"note,omitempty"`
	Client     *Client  `json:"client,omitempty"`
	Product    *Product `json:"product,omitempty"`
}

type SaleInput struct {
	ClientID   string   `json:"clientId"`
	ProductID  *string  `json:"productId,omitempty"`
	Quantity   int32    `json:"quantity"`
	Amount     float64  `json:"amount"`
	PaidAmount *float64 `json:"paidAmount,omitempty"`
	Status     *string  `json:"status,omitempty"`
	Note       *string  `json:"note,omitempty"`
}

type SalesStatus struct {
	Paid    float64 `json:"paid"`
	Pending float64 `json:"pending"`
	Partial float64 `json:"partial"`
}

type Subscription struct {
}

type TopProduct struct {
	Name  string `json:"name"`
	Sales int32  `json:"sales"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}
