package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"bureau/gateway/graph/model"
	"bureau/gateway/internal/models"
	"context"
	"fmt"
)

// ClientTree is the resolver for the clientTree field.
func (r *queryResolver) ClientTree(ctx context.Context, id string) (*model.ClientTree, error) {
	// Appeler le Tree Service
	treeResponse, err := r.Resolver.treeServiceClient.GetClientTree(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get client tree: %w", err)
	}

	// Convertir la réponse du Tree Service en modèle GraphQL
	rootNode := r.convertTreeNode(treeResponse.Root)
	nodes := make([]*model.ClientTreeNode, len(treeResponse.Nodes))
	for i, node := range treeResponse.Nodes {
		nodes[i] = r.convertTreeNode(node)
	}

	return &model.ClientTree{
		Root:       rootNode,
		Nodes:      nodes,
		TotalNodes: treeResponse.TotalNodes,
		MaxLevel:   treeResponse.MaxLevel,
	}, nil
}

// convertTreeNode convertit un TreeNode du service en ClientTreeNode GraphQL
func (r *queryResolver) convertTreeNode(node *models.TreeNode) *model.ClientTreeNode {
	if node == nil {
		return nil
	}

	var cyclesAvailable *int
	if node.CyclesAvailable != nil {
		cycles := *node.CyclesAvailable
		cyclesAvailable = &cycles
	}

	var cyclesPaidToday *int
	if node.CyclesPaidToday != nil {
		cycles := *node.CyclesPaidToday
		cyclesPaidToday = &cycles
	}

	return &model.ClientTreeNode{
		ID:                node.ID,
		ClientID:          node.ClientID,
		Name:              node.Name,
		Phone:             node.Phone,
		ParentID:          node.ParentID,
		Level:             node.Level,
		Position:          node.Position,
		NetworkVolumeLeft: node.NetworkVolumeLeft,
		NetworkVolumeRight: node.NetworkVolumeRight,
		BinaryPairs:       node.BinaryPairs,
		TotalEarnings:     node.TotalEarnings,
		WalletBalance:     node.WalletBalance,
		IsActive:          node.IsActive,
		LeftActives:       node.LeftActives,
		RightActives:      node.RightActives,
		IsQualified:       node.IsQualified,
		CyclesAvailable:   cyclesAvailable,
		CyclesPaidToday:   cyclesPaidToday,
	}
}
